import Admin from "@/components/Admin/Admin";

export const metadata = {
  title: "United furniture uae",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div>
      <Admin>{children}</Admin>
    </div>
  );
}
